pipeline {
    agent any

    environment {
        // Define the Python path if you have a specific version, otherwise it will default to system Python
        PYTHON = 'C:\\Python39\\python.exe'  // Adjust this to your Python installation path
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout your repository containing the pytest test cases
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                script {
                    // Create a virtual environment for Windows
                    bat 'python -m venv venv'  // Create virtual environment

                    // Install dependencies in the virtual environment
                    bat 'venv\\Scripts\\pip install --upgrade pip'  // Upgrade pip
                    bat 'venv\\Scripts\\pip install -r requirements.txt'  // Install dependencies
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run pytest on the specific test case with the required options
                    bat 'venv\\Scripts\\pytest test_cases\\update\\update_headline.py -v -s --browser=chrome'
                }
            }
        }
        
        stage('Publish Results') {
            steps {
                // Archive the test results (optional)
                junit '**/test-*.xml'  // This will collect the XML reports generated by pytest
            }
        }
    }

    post {
        always {
            // Clean up workspace after the pipeline finishes
            cleanWs()  // This will clean up the workspace
        }

        success {
            // Actions to t
